name: Compile PDF

on:
  push: {}

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install fonts
        run: |
          apt update
          apt install --yes \
            fonts-roboto \
            fonts-adobe-sourcesans3 \
            ;

      - name: Generate PDF document
        run: |
          lualatex --jobname="EN - Maciej Hałas - CV" cv.tex

      - uses: actions/upload-artifact@v6
        with:
          name: CV
          path: ./EN - Maciej Hałas - CV.pdf
