name: Build LaTeX CV

on:
  push:
    branches: [ "master", "github-actions" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install fonts
        run: |
          apt update
          apt install --yes \
            fonts-roboto \
            fonts-adobe-sourcesans3 \
            texlive-fonts-extra \
            ;

      - name: Install fontawesome6 using tlmgr
        run: |
          tlmgr update --self
          tlmgr install fontawesome6

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v2.1.0
        with:
          format: pdf
          filename: cv.tex
          options: -pdflatex=lualatex -shell-escape
