name: Compile PDF

on:
  push:
    branches: [ "master", "github-actions" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install fonts
        run: |
          apt update
          apt install --yes \
            fonts-roboto \
            fonts-adobe-sourcesans3 \
            ;

      - name: Generate PDF document
        run: |
          lualatex --jobname="EN - MaciejHalas - CV" cv.tex

      - uses: actions/upload-artifact@v6
        with:
          name: EN - MaciejHalas - CV
          path: ./*.pdf
